INCFLAGS = -I$(CORE_DIR)/lynx -I$(CORE_DIR)/libretro

SOURCES_CXX := $(CORE_DIR)/lynx/lynxdec.cpp \
	$(CORE_DIR)/lynx/cart.cpp \
	$(CORE_DIR)/lynx/memmap.cpp \
	$(CORE_DIR)/lynx/mikie.cpp \
	$(CORE_DIR)/lynx/ram.cpp \
	$(CORE_DIR)/lynx/rom.cpp \
	$(CORE_DIR)/lynx/susie.cpp \
	$(CORE_DIR)/lynx/system.cpp \
	$(CORE_DIR)/libretro/libretro.cpp
